# 01. Numpy

다차원 배열을 효율적으로 처리하는 파이선 라이브러리.

- 파이썬 List보다 빠르고 메모리를 적게 쓴다
- 반복문없이 배열 전체를 한번에 처리한다
- 선형대수 연산을 제공한다

> 작성 환경: numpy 2.5.3 / pandas 3.0.5

---

## 기본 세팅

In [ ]:
import numpy as np

---

## 배열 생성

다차원 배열을 생성하는 기본적인 방법은 array()함수를 사용하는 것
- type은 ndarray객체이다
- 모든 원소가 같은 자료형이어야 한다
- 한번 생성된 배열은 원소의 개수를 변경할 수 없다

In [3]:
arr1 = np.array([7, 2, 9, 10]) # (4,)

arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)

arr3 = np.array([[[1, 2, 3, 4],
                  [3, 4, 5, 6],
                  [5, 6, 7, 8]],
                      [[1, 2, 3, 4],
                      [3, 4, 5, 6],
                      [5, 6, 7, 8]]])  # (2, 3, 4)

---

## 배열 특징

- shape 속성: 배열의 형태를 튜플 자료형으로 표현한다

In [5]:
print("arr1.shape: ", arr1.shape)
print("arr2.shape: ", arr2.shape)
print("arr3.shape: ", arr3.shape)


arr1.shape:  (4,)
arr2.shape:  (2, 3)
arr3.shape:  (2, 3, 4)


- dtype 속성: 배열 원소의 자료형을 나타낸다

In [6]:
print("arr1.dtype: ", arr1.dtype)
print("arr2.dtype: ", arr2.dtype)
print("arr3.dtype: ", arr3.dtype)


arr1.dtype:  int64
arr2.dtype:  int64
arr3.dtype:  int64


- astype 속성: 배열 원소의 데이터 타입을 원하는 다른 타입으로 변환한다

In [42]:
arr = np.array([1, 2, 3])
print("arr: ", arr)
print("arr.dtype: ", arr.dtype)
print("arr.astype('float32'): ", arr.astype('float32'))

arr:  [1 2 3]
arr.dtype:  int64
arr.astype('float32'):  [1. 2. 3.]


---

## 배열 생성 함수

- arange함수 -> np.arange(시작, 끝, 간격)  
주어진 범위내의 연속된 값을 가지는 배열을 생성

In [10]:
arr = np.arange(0, 10, 2) # 0, 2, 4, 6, 8
print(arr) 
type(arr) # numpy.ndarray

[0 2 4 6 8]


numpy.ndarray

- linspace 함수 -> np.linspace(시작, 끝, 개수)  
시작과 끝을 포함해서 지정된 개수만큼 균일한 간격으로 숫자를 생성

In [14]:
arr = np.linspace(0, 4, 5)
print(arr)

[0. 1. 2. 3. 4.]


- zeros 함수 -> np.zeros(형태)  
주어진 형태의 배열을 만들고, 모두 0으로 채운다

In [16]:
arr1 = np.zeros(5)
arr2 = np.zeros((2, 3))
print("arr1: ", arr1)
print("arr2: ", arr2)

arr1:  [0. 0. 0. 0. 0.]
arr2:  [[0. 0. 0.]
 [0. 0. 0.]]


---

## 기본 연산

In [49]:
# 1. 
a = np.array([20, 30, 40, 50])
b = np.arange(4) # array([0, 1, 2, 3])

c = a - b 
print("a: ", a)
print("b: ", b)
print("a-b: ", c)

# 2. 
b**2
print("b**2: ", b**2)

# 3. 
A = np.array([[1, 1],
              [0, 1]])

B = np.array([[2, 0],
              [3, 4]])

A * B
print("A: ", A)
print("B: ", B)
print("A*B: ", A*B)

a:  [20 30 40 50]
b:  [0 1 2 3]
a-b:  [20 29 38 47]
b**2:  [0 1 4 9]
A:  [[1 1]
 [0 1]]
B:  [[2 0]
 [3 4]]
A*B:  [[2 0]
 [0 4]]


### 행렬곱 (@)

`*`는 원소별 곱(같은 자리끼리), `@`는 행렬곱. 서로 다른 연산이다.

- 계산 규칙: 결과[i][j] = A의 i번째 **행** 과 B의 j번째 **열** 을
  순서대로 곱해서 전부 더한 값
- shape 규칙: (a, b) @ (b, c) -> (a, c)
  안쪽 b가 같아야 하고, 계산 후 사라진다
- 순서를 바꾸면 결과가 달라진다 (A @ B ≠ B @ A)

In [50]:
A = np.array([[1, 1],
              [0, 1]])
print("A: ", A)
B = np.array([[2, 0],
              [3, 4]])
print("B: ", B)
A * B    # [[2, 0], [0, 4]]   같은 자리끼리
print("A * B: ", A * B)
A @ B    # [[5, 4], [3, 4]]   행 x 열
print("A @ B: ", A @ B)

A:  [[1 1]
 [0 1]]
B:  [[2 0]
 [3 4]]
A * B:  [[2 0]
 [0 4]]
A @ B:  [[5 4]
 [3 4]]


In [51]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("1차원끼리면 결과는 숫자 하나 (내적)")
print("a: ", a)
print("b: ", b)
a @ b    # 32
print("a @ b: ", a @ b)
a * b    # [4, 10, 18]
print("a * b: ", a * b)

1차원끼리면 결과는 숫자 하나 (내적)
a:  [1 2 3]
b:  [4 5 6]
a @ b:  32
a * b:  [ 4 10 18]


---

## 형태 변경

- reshape 함수 -> reshape(형태)  
데이터의 전체 개수는 그대로 유지하면서 행과 열의 모양만 바꾼다
(원본은 유지)

In [21]:
arr = np.arange(18)
print("arr: ", arr)
print()
arr_reshape1 = arr.reshape(3, 6) # 18열의 데이터를 3행 6열의 데이터로 변환
print("arr_reshape1: ", arr_reshape1)
print()
# -1은 프로그램이 알아서 할당
arr_reshape2 = arr.reshape(-1, 2, 3) # 3페이지 2행 3열의 데이터로 변환
print("arr_reshape2: ", arr_reshape2)
print()
# reshape(-1)는 1차원 벡터로 펼침
arr_reshape3 = arr.reshape(-1)
print("arr_reshape3: ", arr_reshape3)

arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]

arr_reshape1:  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

arr_reshape2:  [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]

arr_reshape3:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


---

## 인덱싱과 슬라이싱

In [25]:
arr = np.arange(3, 9) # [3, 4, 5, 6, 7, 8]
print(arr)
print()
arr[3] # 6
print("arr[3]: ", arr[3])
print()
arr[-1] # 8
print("arr[-1]: ", arr[-1])
print()
arr[-2] # 7
print("arr[3]: ", arr[3])
print()

print("arr[0:4]: ", arr[0:4]) # [3, 4, 5, 6]
print()
print("arr[:4]: ", arr[0:4]) # [3, 4, 5, 6]
print()
print("arr[:]: ", arr[:]) # [3, 4, 5, 6, 7, 8]
print()
print("arr[:-1]: ", arr[:-1]) # [3, 4, 5, 6, 7]
print()
print()
arr2 = np.arange(3, 9) # [3, 4, 5, 6, 7, 8]
print("arr2: ", arr2)
print()
arr2 = arr2.reshape(-1, 3) # [[3, 4, 5], [6, 7, 8]]
print("arr2: ", arr2)
print()
print("arr2[0, 0]: ", arr2[0:0]) # 3
print()
print("arr2[1, 2]: ", arr2[1:2]) # 8
print()
print("arr2[:,0]: ", arr2[:,0]) # [3, 6]
print()
print("arr2[0,:]: ", arr2[0,:]) # [3, 4, 5]

[3 4 5 6 7 8]

arr[3]:  6

arr[-1]:  8

arr[3]:  6

arr[0:4]:  [3 4 5 6]

arr[:4]:  [3 4 5 6]

arr[:]:  [3 4 5 6 7 8]

arr[:-1]:  [3 4 5 6 7]


arr2:  [3 4 5 6 7 8]

arr2:  [[3 4 5]
 [6 7 8]]

arr2[0, 0]:  []

arr2[1, 2]:  [[6 7 8]]

arr2[:,0]:  [3 6]

arr2[0,:]:  [3 4 5]


## 논리 인덱싱

In [32]:
arr = np.arange(3, 9) # [3, 4, 5, 6, 7, 8]
print("arr: ", arr, "\n")
print("1.")
idx = np.array([True, False, True, False, True, False])
print("idx: ", idx) # array([True, False, True, False, True, False])
print("arr[idx]: ", arr[idx]) # [3, 5, 7]

print("2.")
print("arr > 5: ", arr > 5) # [False, False, False, True, True, True]
print("arr[arr>5]: ", arr[arr>5]) # [6, 7, 8]

arr:  [3 4 5 6 7 8] 

1.
idx:  [ True False  True False  True False]
arr[idx]:  [3 5 7]
2.
arr > 5:  [False False False  True  True  True]
arr[arr>5]:  [6 7 8]


### np.where - 조건에 따라 값 바꾸기

np.where(조건, 참일 때, 거짓일 때)
- 논리 인덱싱 arr[arr>5] : 조건에 맞는 것만 **뽑는다** (개수 줄어듦)
- np.where           : 조건에 따라 값을 **바꾼다** (개수 그대로)


In [48]:
arr = np.array([3, 6, 8])
print("arr: ", arr)
arr[arr > 5]  
print("arr[arr>5]: ", arr[arr>5])              # [6, 8]
np.where(arr > 5, 1, 0)     # [0, 1, 1]
print("np.where(arr>5, 1, 0): ", np.where(arr > 5, 1, 0))

arr:  [3 6 8]
arr[arr>5]:  [6 8]
np.where(arr>5, 1, 0):  [0 1 1]


---

## 통계함수

In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("arr: ", arr, "\n")
print("arr.sum(): ", arr.sum()) # 21
# axis=0 -> 사라지는 축
print("arr.sum(axis=0): ", arr.sum(axis=0)) # [5, 7, 9]
# axis=1 -> 사라지는 축
print("arr.sum(axis=1): ", arr.sum(axis=1)) # [6, 15]
print()

print('arr.mean(): ', arr.mean())          # 3.5      전체 평균
print('arr.mean(axis=0): ', arr.mean(axis=0))    # [2.5, 3.5, 4.5]   0번 축 사라짐 -> 열별 평균
print('arr.std(): ', arr.std())           # 표준편차: 값들이 평균에서 얼마나 흩어져 있는가

arr:  [[1 2 3]
 [4 5 6]] 

arr.sum():  21
arr.sum(axis=0):  [5 7 9]
arr.sum(axis=1):  [ 6 15]

arr.mean():  3.5
arr.mean(axis=0):  [2.5 3.5 4.5]
arr.std():  1.707825127659933


### 위치 찾기 (argmax/argmin)

max는 "값", argmax는 "그 값의 위치(인덱스)"를 반환한다.

In [45]:
arr = np.array([3, 9, 1, 7])
print("arr: ", arr)
print("arr.max(): ", arr.max())
print("arr.argmax(): ", arr.argmax())

arr:  [3 9 1 7]
arr.max():  9
arr.argmax():  1


## 난수 생성

- 기본 세팅

In [34]:
import numpy as np
np.random.seed(42)

- rand 함수 -> np.rand(d0, d1, d2...)  
0이상 1미만 난수 생성

In [38]:
# 1차원 배열 난수 5개 뽑기
arr = np.random.rand(5)
print("np.random.rand(5): ", arr)
# 2차원 배열 3행 2열의 난수 6개 뽑기
matrix = np.random.rand(3, 2)
print("np.random.rand(3, 2): ", matrix)

np.random.rand(5):  [0.23089383 0.24102547 0.68326352 0.60999666 0.83319491]
np.random.rand(3, 2):  [[0.17336465 0.39106061]
 [0.18223609 0.75536141]
 [0.42515587 0.20794166]]


- randint 함수 -> np.random.randint(시작, 끝, 사이즈)  
정수 난수 생성

In [36]:
# 0이상 10미만의 정수 1개만 뽑기
num = np.random.randint(10)
print("np.random.randint(10): ", num)
# 1 이상 45 이하의 로또 번호 6개
lotto = np.random.randint(1, 46, 6) # 1차원 배열 생성
print("np.random.randint(1, 46, 6): ", lotto)
# 0 이상 10 미만의 숫자로 2행 3열 구성
matrix = np.random.randint(0, 10, (2, 3)) # 2차원 배열 생성
print("np.random.randint(0, 10, (2, 3)): ", matrix)

np.random.randint(10):  7
np.random.randint(1, 46, 6):  [24  3 22  2 24 44]
np.random.randint(0, 10, (2, 3)):  [[5 1 4]
 [0 9 5]]


- randn 함수 -> np.random.randn(d0, d1, d2...)  
평균 0, 분산 1인 난수 생성

In [37]:
# 1차원 배열 난수 7개 뽑기
arr = np.random.randn(7)
print("np.random.randn(7): ", arr)
# 2차원 배열 2행 4열의 난수 8개 뽑기
matrix = np.random.randn(2, 4)
print("np.random.randn(2, 4): ", matrix)

np.random.randn(7):  [-2.43910582  0.60344123 -0.25104397 -0.16386712 -1.47632969  1.48698096
 -0.02445518]
np.random.randn(2, 4):  [[ 0.35555132  0.41701111  0.83246186 -0.29339915]
 [-0.02983857  0.09512578  0.66465434 -0.1402185 ]]


---

## 브로드캐스팅

모양이 서로 다른 배열끼리 연산을 할 수 있도록, 작은 배열을 큰 배열의 모양에 맞춰 자동으로 확장해 주는 기능  

브로드캐스팅 조건:

1. 두 배열의 축 크기가 완벽히 같거나,
2. 둘 중 하나의 축 크기가 무조건 1이어야 한다.
3. 또는 오른쪽 끝 축부터 짝을 맞추고, 모자라는 왼쪽 자리는 1로 채운다.

In [40]:
matrix = np.array([[10, 20, 30], [40, 50, 60]])
print("matrix: ", matrix)
arr = np.array([1, 2, 3])
print("arr: ", arr)

result = matrix + arr
print("matrix+arr: ", result, "\n")
# (2, 3) vs (3,) 성공 -> (2, 3)
# result -> [[11, 22, 33], [41, 52, 63]]

arr1 = np.array([[1], [2], [3]])
print("arr1: ", arr1)
arr2 = np.array([[1, 2, 3, 4]])
print("arr2: ", arr2)
result = arr1 + arr2
print("arr1+arr2: ", result)
# (3, 1) vs (1, 4) 성공 -> (3, 4)
# arr1 = [[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]]
# arr2 = [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]
# result -> [[2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7]]

matrix:  [[10 20 30]
 [40 50 60]]
arr:  [1 2 3]
matrix+arr:  [[11 22 33]
 [41 52 63]] 

arr1:  [[1]
 [2]
 [3]]
arr2:  [[1 2 3 4]]
arr1+arr2:  [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
